# Generated by Django 2.1.3 on 2019-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpgenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.CharField(max_length=40, unique=True)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='status_choice',
            field=models.CharField(choices=[('R', 'RUNNING'), ('P', 'PLAYED'), ('W', 'WAITING')], default='WAITING', max_length=8),
        ),
    ]
