# Generated by Django 2.1.3 on 2019-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumenapp', '0002_auto_20190306_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpgenerator',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpgenerator',
            name='mailid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
